"""
Django settings for qr_service project.
 
Generated by 'django-admin startproject' using Django 5.2.10.
 
For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
 
import os
# import dj_database_url
from pathlib import Path
from tools_box.config.settings import CoreConfigReader
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.

ENVIRONMENT = CoreConfigReader.get_config("ENVIRONMENT", default="local")
SERVICE_NAME = CoreConfigReader.get_config("SERVICE_NAME", default='qr')

BASE_DIR = Path(__file__).resolve().parent.parent.parent
 

SECRET_KEY = CoreConfigReader.get_config(
    "SECRET_KEY"
)

DEBUG = CoreConfigReader.get_config("DEBUG", type_hint=bool, default=False)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
ALLOWED_HOSTS =[]
 

 
INSTALLED_APPS = [
    'daphne',
    'channels',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'corsheaders',  
    'rest_framework',
    'apps.qr'
]
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "tools_box.auth_backends.auth_trust.MiddlewareTrustedAuthentication",
    ],
    "EXCEPTION_HANDLER": "tools_box.utils.exceptions.app_exception_handler",
    "UNAUTHENTICATED_USER": "django.contrib.auth.models.AnonymousUser",
    "DEFAULT_RENDERER_CLASSES": (
        "tools_box.utils.renderers.SuccessJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "tools_box.utils.pagination.SmallResultsSetPagination",
    "PAGE_SIZE": CoreConfigReader.get_config("PAGE_SIZE", type_hint=int, default=20),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # 'DEFAULT_AUTHENTICATION_CLASSES': (
    #     'rest_framework.authentication.SessionAuthentication',
    #     'rest_framework.authentication.BasicAuthentication',
    #     'rest_framework.authentication.TokenAuthentication',
    # ),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "tools_box.middleware.logging.request_logging.RequestLoggingMiddleware",
    "tools_box.middleware.logging.sql_logging.SQLLoggingMiddleware",
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
ROOT_URLCONF = 'core.urls'
 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
ASGI_APPLICATION = 'core.asgi.application'
WSGI_APPLICATION = 'core.wsgi.application'
 
REDIS_URL =CoreConfigReader.get_config(
    "REDIS_URL", 
    default="redis://127.0.0.1:6379"
)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}



LANGUAGE_CODE = 'en-us'
 
TIME_ZONE = 'UTC'
 
USE_I18N = True
 
USE_TZ = True
 
 

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 

from .helpers import configure_logging
configure_logging()

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
 

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# database_url = CoreConfigReader.get_config(
#     "DATABASE_URL", 
#     default="sqlite:///db.sqlite3"
# )
# DATABASES['default'] = dj_database_url.parse(database_url)
 
 
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
 # Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
 
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'